apiVersion: v1
kind: Service
metadata:
  name: order-management-service
  labels:
    app: order-management-system
spec:
  type: NodePort
  selector:
    app: order-management-system
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
